version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:9d:2e:c5:be:ce:a6:e0:48:62:58:73:9b:a7:4c:dc"
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run gh-pages-clean
            - run: npm run deploy
            - run: echo "TODO add tests"
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        filters:
            branches:
              only: source
