version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:9d:2e:c5:be:ce:a6:e0:48:62:58:73:9b:a7:4c:dc"
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run deploy
      - run:
          command: echo "TODO add tests"
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        filters:
            branches:
              only: source
