version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ffXN5tad3STQqoHUK3PDo1XjubPJk0lEhZ5RwAhJLFA"
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run gh-pages-clean
      - run:
          command: npm run deploy
      - run:
          command: echo "TODO add tests"
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        filters:
            branches:
              only: source
